### ISSUE TITLE
Helm 2.9.1 also refusing connection with minikube...

### ISSUE THREAD

**Issue by kaiwaehner** [confluentinc/cp-helm-charts#107]
I followed all steps, but "helm list" still refusing connection even thought the read me says that only before 2.9.1. these issues exist. Though, the documented workaround does not work, unfortunately. 

Here are my steps (I tried it twice):

kai.waehner@Kais-MacBook-12:~|⇒  kubectl cluster-info
Kubernetes master is running at https://192.168.99.100:8443

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
kai.waehner@Kais-MacBook-12:~|⇒  clear
kai.waehner@Kais-MacBook-12:~|⇒  helm init
$HELM_HOME has been configured at /Users/kai.waehner/.helm.
Warning: Tiller is already installed in the cluster.
(Use --client-only to suppress this message, or --upgrade to upgrade Tiller to the current version.)
Happy Helming!
kai.waehner@Kais-MacBook-12:~|⇒  helm repo update
Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Successfully got an update from the "coreos" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈ Happy Helming!⎈
kai.waehner@Kais-MacBook-12:~|⇒  helm list
Error: Get https://10.96.0.1:443/api/v1/namespaces/kube-system/configmaps?labelSelector=OWNER%!D(MISSING)TILLER: dial tcp 10.96.0.1:443: i/o timeout
kai.waehner@Kais-MacBook-12:~|⇒  kubectl delete --namespace kube-system svc tiller-deploy
service "tiller-deploy" deleted
kai.waehner@Kais-MacBook-12:~|⇒  kubectl delete --namespace kube-system deploy tiller-deploy
deployment "tiller-deploy" deleted
kai.waehner@Kais-MacBook-12:~|⇒  kubectl create serviceaccount --namespace kube-system tiller
Error from server (AlreadyExists): serviceaccounts "tiller" already exists
kai.waehner@Kais-MacBook-12:~|⇒  kubectl create clusterrolebinding tiller-cluster-rule --clusterrole=cluster-admin --serviceaccount=kube-system:tiller
Error from server (AlreadyExists): clusterrolebindings.rbac.authorization.k8s.io "tiller-cluster-rule" already exists
kai.waehner@Kais-MacBook-12:~|⇒  kubectl patch deploy --namespace kube-system tiller-deploy -p '{"spec":{"template":{"spec":{"serviceAccount":"tiller"}}}}'
Error from server (NotFound): deployments.extensions "tiller-deploy" not found
kai.waehner@Kais-MacBook-12:~|⇒  helm init --service-account tiller --upgrade
$HELM_HOME has been configured at /Users/kai.waehner/.helm.

Tiller (the Helm server-side component) has been installed into your Kubernetes Cluster.

Please note: by default, Tiller is deployed with an insecure 'allow unauthenticated users' policy.
For more information on securing your installation see: https://docs.helm.sh/using_helm/#securing-your-helm-installation
Happy Helming!
kai.waehner@Kais-MacBook-12:~|⇒  helm install --name my-confluent-oss cp-helm-charts
Error: failed to download "cp-helm-charts" (hint: running `helm repo update` may help)
kai.waehner@Kais-MacBook-12:~|⇒  helm repo update
Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Successfully got an update from the "coreos" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈ Happy Helming!⎈
kai.waehner@Kais-MacBook-12:~|⇒  helm install --name my-confluent-oss cp-helm-charts
Error: failed to download "cp-helm-charts" (hint: running `helm repo update` may help)
kai.waehner@Kais-MacBook-12:~|⇒  helm list
Error: Get https://10.96.0.1:443/api/v1/namespaces/kube-system/configmaps?labelSelector=OWNER%!D(MISSING)TILLER: dial tcp 10.96.0.1:443: i/o timeout
kai.waehner@Kais-MacBook-12:~|⇒  helm version
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
kai.waehner@Kais-MacBook-12:~|⇒

**Comment by kanolato** [comment]
You could try `helm init --service-account default` instead of just `helm init`

**Comment by milanvdm** [comment]
I have exactly the same issue:
```
 minikube start --vm-driver=hyperkit
Starting local Kubernetes v1.10.0 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Starting cluster components...
Kubectl is now configured to use the cluster.
Loading cached images from config file.
╭─  ~                                                                                                                                                                                                                 57.75   01:13:33 
╰ helm init
$HELM_HOME has been configured at /Users/milanvandermeer/.helm.
Warning: Tiller is already installed in the cluster.
(Use --client-only to suppress this message, or --upgrade to upgrade Tiller to the current version.)
Happy Helming!
╭─  ~                                                                                                                                                                                                                          01:13:38 
╰ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈ Happy Helming!⎈
╭─  ~                                                                                                                                                                                                                          01:13:52 
╰ helm install cp-helm-charts
Error: failed to download "cp-helm-charts" (hint: running `helm repo update` may help)
```

**Comment by Keerthi4308** [comment]
I ran into the same error and above-suggested instruction didn't work for me. I keep getting this error when I try to run helm install confluentinc/cp-helm-charts : " Error: failed to download "confluentinc/cp-helm-charts" (hint: running `helm repo update` may help)"

**Comment by abhirockzz** [comment]
any resolution ? I am facing the same issue

**Comment by aaron-comyn** [comment]
For anyone else that bumped into this, checkout: https://github.com/confluentinc/cp-helm-charts/issues/199 

The repo was down for a minute.  Afterwards note that "confluentinc" has been changed to "confluent" :)
