### ISSUE TITLE
Links broken

### ISSUE THREAD

**Issue by kanolato** [confluentinc/cp-helm-charts#122]
All of the file's links are broken 
https://github.com/confluentinc/cp-helm-charts/blob/master/docs/index.rst
For example:
- The link to the KSQL example
- The link to the values.yaml

**Comment by gAmUssA** [comment]
@joel-hamill should we replace relative links to `values.yml` with absolute? 
It looks like our docs pipeline doesn't support relative links.

**Comment by joel-hamill** [comment]
The place to view the rendered cp-helm charts documentation is at https://docs.confluent.io/current/quickstart/cp-helm-charts/docs/index.html, so the links are optimized for that location - not GitHub. So on that page the KSQL link works, the YAML currently doesn't. Here's a PR to fix the YAML link: https://github.com/confluentinc/cp-helm-charts/pull/123.

**Comment by gAmUssA** [comment]
Thanks @joel-hamill !
@kanolato I'm closing is as per #123 and @joel-hamill comment

**Comment by kanolato** [comment]
Nice!
