### ISSUE TITLE
Consider adding heapOptions for kafka-connect, etc.

### ISSUE THREAD

**Issue by thomas** [confluentinc/cp-helm-charts#130]
Just an ease of use thing, not really a bug, I've already worked around it for myself:

Kafka & Zookeeper have pretty optimized heap settings by default (512M). Kafka-connect, on the other hand, is gobbling up quite a bit on startup, at least 1G, which was enough to cause issues in my (very small) test cluster.

May save a lot of confusion and support requests to throw a heapOptions option in for other java portions of the app as well, and default it to a lower value.

**Comment by gAmUssA** [comment]
Hello @thomas 
Thanks for that.
Have you considered send PR?
