### ISSUE TITLE
Unable to install new connector plugins in kafka connect 

### ISSUE THREAD

**Issue by mickael83** [confluentinc/cp-helm-charts#138]
Hi,

I successfully deployed kafka confluent platform into my minikube cluster using this helm chart and I successfully added new connector configuration using the JdbcSourceConnector with a postgresql configuration.

I am now struggling to add a new connector configuration using the JdbcSourceConnector for an SQLServer database. I already downloaded the mssql driver (mssql-jdbc-7.0.0.jre8.jar) and placed it into `/usr/share/java/kafka-connect-jdbc` directory but I keep getting the following error:

`
"Invalid value java.sql.SQLException: No suitable driver found for jdbc:sqlserver://mssql-dev.mydomain.pt:1433;database=mydb;user=user_dev;password=user_pass for configuration Couldn't open connection to jdbc:sqlserver://mssql-dev.mydomain.pt:1433;database=mydb;user=user_dev;password=user_pass"
`

I also tried to install a third party plugin using the command `confluent-hub install debezium/debezium-connector-mysql:0.8.1` however the plugin seems not to be loaded by connect because it is not listed when requesting the /connector-plugins API.

Considering that the kafka connect process is launched when the container is started (/etc/confluent/docker/run) I was wondering if the third party plugins and jdbc drivers are supposed to be present at launch. If this is the case, how can I do that? 

Any help would be appreciated.

**Comment by wktmeow** [comment]
Found the same thing, added PR: https://github.com/confluentinc/cp-helm-charts/pull/160

**Comment by mixja** [comment]
The custom connectors need to be in the plugin directory at Connect startup.

You can do this using either of the following approaches:

1.  Create a custom Docker image based from confluentinc/cp-kafka-connect:

```
FROM confluentinc/cp-kafka-connect:5.0.0
COPY <path-to-jars>/usr/share/java/kafka-connect-jdbc
```

2.  Mount a volume that includes the connectors into your Connect container.  E.g. you could mount an empty volume to an initContainer that downloads and copies the connector to the volume, and then mount the same volume to your Connect container.

IMHO Option 1 is the better approach but requires you to publish a new Docker repository.
