### ISSUE TITLE
Generic environmental options for every deployment

### ISSUE THREAD

**Issue by maver1ck** [confluentinc/cp-helm-charts#140]
Please add this section to every deployment:
```          env:
          {{- range $key, $value := .Values.env }}
          - name: "{{ $key }}"
            value: "{{ $value }}"
          {{- end }}
```
This will give possibility to add configure any env variable.

**Comment by gAmUssA** [comment]
Hello
@maver1ck kindly, send PR!

**Comment by maver1ck** [comment]
OK.
Work in progress...

**Comment by qshao-pivotal** [comment]
Plz note that the docker images (confluent docker images) we are using have
their own logic about setting params. I highly recommend you investigating
into images’ docker file first before making this a PR. Maybe dockerfile is
the better place to add related changes.
Maciej Bryński <notifications@github.com>于2018年9月14日 周五下午3:11写道：

**Comment by maver1ck** [comment]
I just want to add possibility to set arbitrary env variable.

**Comment by maver1ck** [comment]
@gAmUssA @qshao-pivotal 
I'm thinking about sth like this.
https://github.com/confluentinc/cp-helm-charts/pull/146/files
If it's OK I can continue with the rest of charts.
