### ISSUE TITLE
add optional imagePullSecrets

### ISSUE THREAD

**Issue by CrystalMethod** [confluentinc/cp-helm-charts#148]
We would like to use custom Docker images. The current configuration allows you to specify ``image`` and ``imageTag`` for each of the sub-charts. When using a private registry the download of the image fails as expected. Accordingly we have extended the templates with the optional declaration of ``imagePullSecrets``, e.g. ``{{- if .Values.global.imagePullSecrets }}...{{- end }}``. Would that be of general interest for a PR?

**Comment by gAmUssA** [comment]
@CrystalMethod Lars, this is fantastic idea for PR.
Thanks

**Comment by CrystalMethod** [comment]
Fine, will do so.
