### ISSUE TITLE
Documentation for monitoring part (Grafana) is incorrect and incomplete

### ISSUE THREAD

**Issue by kaiwaehner** [confluentinc/cp-helm-charts#185]
Problems with configuring the monitoring as described in the docs under section "monitoring".

I have installed prometheus and grafana as described (step 1). But step 2 and 3 are incomplete / incorrect.

Step 2: 
Add Prometheus as Data Source in Grafana, url should be something like: http://illmannered-marmot-prometheus-server:9090
=> I have no idea what to do here and what "something like" means

Step 3:
Import dashboard under grafana-dashboard into Grafana 
=> The link does not work and refers to landing page of Confluent docs.

![image](https://user-images.githubusercontent.com/813987/48425394-07994b00-e765-11e8-8420-c899a6f0c98a.png)

https://docs.confluent.io/current/installation/installing_cp/cp-helm-charts/docs/index.html

**Comment by qshao-pivotal** [comment]
Would you mind sending a PR to correct and complete it?

**Comment by hendrikhalkow** [comment]
Fully agree, Kai. The URL should be like http://prometheus-server.<namespace>.svc.cluster.local. That works somehow as long as I don't check the 'default' checkbox. I can see the Prometheus Data in the Prometheus dashboard. However, the Confluent dashboard shows totally random data. The following screenshots were taken within a couple of seconds.

<img width="765" alt="screenshot 2018-12-12 at 01 20 05" src="https://user-images.githubusercontent.com/205553/49838684-26165480-fdac-11e8-8125-5f40079d4614.png">
<img width="871" alt="screenshot 2018-12-12 at 01 20 23" src="https://user-images.githubusercontent.com/205553/49838686-27e01800-fdac-11e8-8767-6d49aa6ae813.png">

**Comment by michaelswierszcz** [comment]
why was this issue closed?
