### ISSUE TITLE
Published cp-helm-charts-0.1.0.tgz is old and doesn't have latest fixes and commits.

### ISSUE THREAD

**Issue by kurtostfeld** [confluentinc/cp-helm-charts#233]
Doing either

`helm fetch --debug confluent/cp-helm-charts`

or

`curl -O https://confluentinc.github.io/cp-helm-charts/cp-helm-charts-0.1.0.tgz`

results in an old chart archive that doesn't have the latest fixes. I was specifically looking for the following commit fix: https://github.com/confluentinc/cp-helm-charts/commit/4c17ac3023f193118545e552da5d7ca85eb6a25a

I can verify I get the old version with:

`tar xfO cp-helm-charts-0.1.0.tgz cp-helm-charts/charts/cp-kafka/templates/statefulset.yaml | grep -n -C10 volumes:`

I get the same outcome if I do a `helm install confluent/cp-helm-charts` and look at the archive `~/.helm/cache/archive/cp-helm-charts-0.1.0.tgz`

**Comment by gAmUssA** [comment]
@kurtostfeld work on automatic build and versioning of helm charts is still in progress. 
as workaround I recommend to have a local copy of repo and build charts locally.
Thank you
