### ISSUE TITLE
Document process for resource requirements

### ISSUE THREAD

**Issue by gwenshap** [confluentinc/cp-helm-charts#24]
Kubernetes and Helm allow users to require and/or limit resources for each component. For example, we recommend 4GB RAM for Kafka Broker, so it will be good to let Kubernetes know, so brokers can be allocated on nodes with enough resources.

We don't need to have these by default (so our charts will be useful for tiny deployments), but we want to let people know they can and should do it for production, and how to do it.

**Comment by Tenseiga** [comment]
HI Team,
I cannot find your repo. Is the chart published to some repository? so that I can add ?
