### ISSUE TITLE
Add external routing for Kafka

### ISSUE THREAD

**Issue by gwenshap** [confluentinc/cp-helm-charts#25]
We will want to provide the option to produce/consume to Kafka from outside Kubernetes.

**Comment by deepaksood619** [comment]
In Azure, nodes do not get external ip, so how we can use NodePorts in that scenario? How can we use LoadBalancer to access kafka from outside cluster?

**Comment by deepaksood619** [comment]
What is the difference between service and headless-service. We can use headless-service for connecting to broker from clients inside the cluster, then what is the use case of service?
