### ISSUE TITLE
Confluent Kafka operator on on-prem Kubernetes 

### ISSUE THREAD

**Issue by himanshurajput32** [confluentinc/cp-helm-charts#313]
Hi

Can we use Confluent kafka operator over a self-managed on-prem Kubernetes cluster (v1.13)?
I found a list of providers supported by confluent operator-
https://docs.confluent.io/current/installation/operator/index.html#co-long

According to this list It's not supported but I was going through a blog from @kaiwaehner 
https://dzone.com/articles/kafka-operator-for-kubernetes-confluent-operator-t

I am little confused on this.

**Comment by kaiwaehner** [comment]
First of all, Confluent Operator is not related to this project here (Open Source Confluent Helm Charts). 

You can use Confluent Operator with any Kubernetes distribution (including self-managed vanilla K8s). 
However, as the Confluent Operator docs say, you need to run Kubernetes 1.9+ (I think 1.3 did not support the required concepts / features).

**Comment by himanshurajput32** [comment]
Thanks @kaiwaehner. 
Does this operator require any license and comes with commercial version only?

**Comment by kaiwaehner** [comment]
Yes. Confluent Operator is a commercial product. Only 30 day trial and single node laptop version is free.

**Comment by himanshurajput32** [comment]
Thanks @kaiwaehner 
Will contact sales team for the cost.
