### ISSUE TITLE
Mounting a Volume or Secret to Kafka Connect

### ISSUE THREAD

**Issue by iamyojimbo** [confluentinc/cp-helm-charts#328]
Maybe I'm missing something here, but say that I want to mount my own volume or secret to a Kafka Connect container, there seems to be no way in the template.

I need to mount a secret to use with the Google BigQuery connector, but there seems to be no way without somehow editing the template/forking the repo etc...

Any easy solution to this? Seems like something others want to do.

**Comment by chelomontilla** [comment]
Yeah, same problem to connect to aws s3, customEnv doesn't have a way to specify secrets. Any help or idea ?
