### ISSUE TITLE
Kafka-Rest Jmx config is incorrect

### ISSUE THREAD

**Issue by samatspothero** [confluentinc/cp-helm-charts#329]
Docker image is expecting configuration to be specified as KAFKAREST_JMX_PORT

https://github.com/confluentinc/cp-helm-charts/blob/5dc3317b75812f8268fa2aed26ec332ff02e8a63/charts/cp-kafka-rest/templates/deployment.yaml#L84

**Comment by cricket007** [comment]
It's not loaded into the config file, so it's actually just JMX_PORT

https://github.com/confluentinc/kafka-rest/blob/master/bin/kafka-rest-run-class#L53

**Comment by gAmUssA** [comment]
CLOSED by #470
