### ISSUE TITLE
The Pod were not working when installed the charts 

### ISSUE THREAD

**Issue by bjlvfei** [confluentinc/cp-helm-charts#354]
Hi Team,
I'm using the Helm to install the chart cp-helm-charts as wiki described 
helm install --name sr confluentinc/cp-helm-charts --namespace confluent
some pods were not working

kubectl get pods --namespace confluent
NAME READY STATUS RESTARTS AGE
sr-cp-kafka-0 1/2 CrashLoopBackOff 60 5h32m
sr-cp-kafka-1 1/2 CrashLoopBackOff 60 5h32m
sr-cp-kafka-2 2/2 Running 61 5h32m
sr-cp-kafka-connect-7b87ffd849-qp26d 1/2 CrashLoopBackOff 60 5h32m
sr-cp-kafka-rest-58b44bdf4f-2c279 1/2 CrashLoopBackOff 60 5h32m
sr-cp-ksql-server-6fb68769bc-vfh4l 1/2 CrashLoopBackOff 62 5h32m
sr-cp-schema-registry-85f74b7884-gvn8c 1/2 CrashLoopBackOff 61 5h32m
sr-cp-zookeeper-0 0/2 Pending 0 5h32m

log for pod sr-cp-kafka-0 as below
java.nio.channels.UnresolvedAddressException
at sun.nio.ch.Net.checkAddress(Net.java:101)
at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:622)
at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277)
at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287)
at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1021)
at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1064)
[main] ERROR io.confluent.admin.utils.ClusterStatus - Timed out waiting for connection to Zookeeper server [sr-cp-zookeeper-headless:2181].
[main-SendThread(sr-cp-zookeeper-headless:2181)] INFO org.apache.zookeeper.ClientCnxn - Opening socket connection to server sr-cp-zookeeper-headless:2181. Will not attempt to authenticate using SASL (unknown error)
[main] INFO org.apache.zookeeper.ZooKeeper - Session: 0x0 closed
[main-EventThread] INFO org.apache.zookeeper.ClientCnxn - EventThread shut down for session: 0x0

log for pod sr-cp-schema-registry-85f74b7884-gvn8c as below
java.io.IOException: Can't resolve address: sr-cp-kafka-headless:9092

log for pod sr-cp-zookeeper-0
Warning FailedScheduling 22m (x245 over 5h38m) default-scheduler 0/12 nodes are available: 12 node(s) had no available volume zone.

Any ideas about this error for pod sr-cp-zookeeper-0? I think kafka and schema-registry which has
a dependency with zookeeper.

Levi
Thanks!

**Comment by cricket007** [comment]
Please show the logs of the Zookeeper pod

**Comment by cricket007** [comment]
Is your cluster healthy?

> 0/12 nodes are available: 12 node(s) had no available volume zone

**Comment by bjlvfei** [comment]
Yes, it's healthy.

**Comment by bjlvfei** [comment]
✘ lvfei@lvfeis-mbp  ~/Documents/confluent/cp-helm-charts   master  kubectl get events -n confluent   
LAST SEEN   TYPE      REASON             OBJECT                                       MESSAGE
94s         Warning   BackOff            pod/sr-cp-kafka-0                            Back-off restarting failed container
81s         Warning   BackOff            pod/sr-cp-kafka-1                            Back-off restarting failed container
75s         Warning   BackOff            pod/sr-cp-kafka-2                            Back-off restarting failed container
86s         Warning   BackOff            pod/sr-cp-kafka-connect-7b87ffd849-qp26d     Back-off restarting failed container
93s         Warning   BackOff            pod/sr-cp-kafka-rest-58b44bdf4f-2c279        Back-off restarting failed container
26m         Normal    Pulled             pod/sr-cp-ksql-server-6fb68769bc-vfh4l       Container image "confluentinc/cp-ksql-server:5.0.1" already present on machine
94s         Warning   BackOff            pod/sr-cp-ksql-server-6fb68769bc-vfh4l       Back-off restarting failed container
90s         Warning   BackOff            pod/sr-cp-schema-registry-85f74b7884-gvn8c   Back-off restarting failed container
31s         Warning   FailedScheduling   pod/sr-cp-zookeeper-0                        0/12 nodes are available: 12 node(s) had no available volume zone.

**Comment by cricket007** [comment]
I'm not sure it is... The Zookeeper volumes aren't being mounted

**Comment by bjlvfei** [comment]
✘ lvfei@lvfeis-mbp  ~ kubectl get pvc -n confluent    
NAME                           STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS       AGE
datadir-0-sr-cp-kafka-0        Bound    pvc-c3d2a60c-0f4d-11ea-ac21-6a812fa2a75a   20Gi       RWO            ibmc-file-bronze   7d19h
datadir-0-sr-cp-kafka-1        Bound    pvc-0d3b783c-0f4e-11ea-ac21-6a812fa2a75a   20Gi       RWO            ibmc-file-bronze   7d19h
datadir-0-sr-cp-kafka-2        Bound    pvc-516b3fcd-0f4e-11ea-ac21-6a812fa2a75a   20Gi       RWO            ibmc-file-bronze   7d19h
datadir-sr-cp-zookeeper-0      Bound    pvc-c3f013be-0f4d-11ea-ac21-6a812fa2a75a   20Gi       RWO            ibmc-file-bronze   7d19h
datalogdir-sr-cp-zookeeper-0   Bound    pvc-c3ecf172-0f4d-11ea-ac21-6a812fa2a75a   20Gi       RWO            ibmc-file-bronze   7d19h


I think the last two were Zookeeper's volumes. Does is correct?

**Comment by bjlvfei** [comment]
The kafka pod is working now! I using the correct broker and schema registry url for kafka connect.

helm install --name connect  --namespace es ./cp-kafka-connect --set kafka.bootstrapServers="PLAINTEXT://cp-kafka-headless:9092",cp-schema-registry.url="schema-schema-registry:8081"
