### ISSUE TITLE
Do regular releases

### ISSUE THREAD

**Issue by cgiraldo** [confluentinc/cp-helm-charts#362]
Hi,
Can you make regular releases of the charts and serve all of them in your helm repo?

It would be nice to install kafka through helm CLI from your helm repo, but actually the only chart in the repo (/docs folder) is version 0.1.0 from Dec 2018.

I would like to use current charts that are compatible with kubernetes 1.16, but I would like to install it from your helm repo and not the source code.

Thanks!

**Comment by gAmUssA** [comment]
I will take a look on tidying this repo up after ok will be back from paternity leave next week.
As a reminder, It's not officially supported repo, hense support is on "best effort" basis.
Thank you for understanding

**Comment by gAmUssA** [comment]
released 0.4.0 for CP 5.4 #369
