### ISSUE TITLE
https://confluentinc.github.io/cp-helm-charts/docs/cp-helm-charts-0.1.0 is no longer available via helm

### ISSUE THREAD

**Issue by ericgoffster** [confluentinc/cp-helm-charts#371]
I see 0.4.0 is available, but it is not backwards compatible

**Comment by ericgoffster** [comment]
my configuration is

**Comment by ericgoffster** [comment]
helm is taking something like:

name: cp-helm-charts
condition: enabled.cp-helm-charts
version: 0.1.0
repository: https://confluentinc.github.io/cp-helm-charts
and adding the docs. What should I be doing differently?

**Comment by gAmUssA** [comment]
DUPLICATE of #370 
Closing
