### ISSUE TITLE
Install cp-kafka (and cp-zookeeper if needed) only

### ISSUE THREAD

**Issue by naseemkullah** [confluentinc/cp-helm-charts#374]
Hello @gAmUssA 👋 , nice to see you here, we met at Cloud Native day Montreal through our common friend @archyufa 😄 

So at Jaeger helm charts, we are looking into installing [OSS kafka as a dependency in the jaeger chart](https://github.com/jaegertracing/helm-charts/issues/27) and are interested in this confluent backed chart, however we only need kafka (and any of it's dependencies, which from my understanding is only `zookeeper`). Is this possible today or can we only install the umbrella chart that includes `shcema-registry`, `control-center`, `connect`, `rest` and `ksql-server` ? Are all these components recommended/needed for OSS Kafka? 

Thanks in advance!

**Comment by mehta-ankit** [comment]
@naseemkullah I think we could use this chart, and disable the components we don't need 🤔

**Comment by naseemkullah** [comment]
Sure, please give that a try @mehta-ankit.

**Comment by gAmUssA** [comment]
@naseemkullah you can definetly use zookeeper and kafka from here. Other components are option. as @mehta-ankit pointed you can disable the components you don't want to use.
Hope this helps

**Comment by naseemkullah** [comment]
Thanks @gAmUssA
