### ISSUE TITLE
How to recover the s3 connector after it's shutdown

### ISSUE THREAD

**Issue by bjlvfei** [confluentinc/cp-helm-charts#412]
Hi Team,

We found the s3 connector was shutdown due to node was not ready for use of k8s. How the S3 connector was recover it by itself? 

[2020-04-11 16:24:34,226] INFO Shutting down S3 connector s3-cos-sink-odsprod.sods1.sales_ord (io.confluent.connect.s3.S3SinkConnector)

Levi
Thanks!

**Comment by cricket007** [comment]
Connectors cannot restart themselves. Whether in k8s or not

**Comment by bjlvfei** [comment]
Thanks @cricket007
