### ISSUE TITLE
Zookeeper Optional Configurations

### ISSUE THREAD

**Issue by qshao-pivotal** [confluentinc/cp-helm-charts#42]
As part of #27 and #26 
In cp-zookeeper image, there are some optional configurations:
https://github.com/confluentinc/cp-docker-images/blob/master/debian/zookeeper/include/etc/confluent/docker/zookeeper.properties.template#L8-L29
Right now we only surfaced 2 config parameters: https://github.com/confluentinc/cp-helm-charts/blob/master/charts/cp-zookeeper/templates/statefulset.yaml#L96-L99

Can we take a look at the parameters and decided which of them should be surfaced and what are the recommended values?

**Comment by maver1ck** [comment]
Maybe better option will be sth like that ?
```
          env:
          {{- range $key, $value := .Values.env }}
          - name: "{{ $key }}"
            value: "{{ $value }}"
          {{- end }}
```
and in values.yaml
```
env:
    ENV_1: abc
```
