### ISSUE TITLE
the meaning of the operator term (confluent operator)

### ISSUE THREAD

**Issue by getElementsByName** [confluentinc/cp-helm-charts#466]
I confuse the [confluent `operator`](https://docs.confluent.io/current/installation/operator/index.html) term and the [k8s `operator`](https://kubernetes.io/docs/concepts/extend-kubernetes/operator/). Are those 2 terms the same? What is the meaning of the `operator` term in the confluent document?

**Comment by gAmUssA** [comment]
Check this vids

https://youtu.be/JiDiC5MI7hw

https://youtu.be/lzFuEuqOSNM

I hope those will clarify some terminology for you

**Comment by getElementsByName** [comment]
@gAmUssA 
Thank you for your guide. It was great videos for me. I got that the confluent operator is k8s operator pattern.
