### ISSUE TITLE
"release" label in grafana dashboard.

### ISSUE THREAD

**Issue by azhang** [confluentinc/cp-helm-charts#468]
https://github.com/confluentinc/cp-helm-charts/blob/3434a1e1ae4992a4c04b528f36408958aab6b07a/grafana-dashboard/confluent-open-source-grafana-dashboard.json#L126

Where does the release label come from? I have confirmed that I receive all the events I'm expecting, but it only contains 
```
container="prometheus-jmx-exporter"
endpoint="metrics"
instance="10.244.1.236:5556"
job="analytics-cp-kafka"
namespace="staging"
pod="analytics-cp-kafka-0"
service="analytics-cp-kafka"
```

**Comment by Jefski14** [comment]
Why was this issue closed? I have the same problem.
