### ISSUE TITLE
Confluent version 6.0.0

### ISSUE THREAD

**Issue by idkw** [confluentinc/cp-helm-charts#476]
Could the charts be updated to support confluent 6.0.0 which has been released recently ?
Thanks !

**Comment by gAmUssA** [comment]
Hey
Highly likely this week
Thanks

**Comment by andrewegel** [comment]
PR https://github.com/confluentinc/cp-helm-charts/pull/477 - @gAmUssA will work on approving & deploying tomorrow.

**Comment by Durairaj** [comment]
@andrewegel  Any update when this can be released?

**Comment by andrewegel** [comment]
You need to ping @gAmUssA - I send the PR, its on him to approve & deploy.

**Comment by Heberth** [comment]
@gAmUssA any progress or updated expected time on this?

**Comment by Durairaj** [comment]
Any progress?

**Comment by gAmUssA** [comment]
released today with CP 6.0.1
