### ISSUE TITLE
A StatefulSet for cp-ksql-server helm chart

### ISSUE THREAD

**Issue by HemanthChalla** [confluentinc/cp-helm-charts#502]
It would be great to have a StatefulSet instead of deployment for ksql-server.

The replica's of ksql-server are not able to communicate with each other on the Kubernetes cluster as they are not part of a StatefulSet leading to failure of pull queries.

Either of the two errors occurs:
1. Exhausted standby nodes to try
2. All nodes are dead or exceed max allowed lag

These errors occur because the replica's of the ksql server can't talk to each other in the cluster.

**Comment by Taymindis** [comment]
Is this issue fixed? I don't see any statefulset of KSQL
