### ISSUE TITLE
Patch log4j

### ISSUE THREAD

**Issue by griseau** [confluentinc/cp-helm-charts#573]
Hello guys, 

Do you plan to release a docker image fixing the log4j security breach ? 

Thanks

**Comment by patros-ki** [comment]
Hi. Yes I would also like to know whether an updated image to fix the log4j2 vulnerability, will be provided. Would you be providing one?

**Comment by gAmUssA** [comment]
better to ask here https://github.com/confluentinc/kafka-images @griseau @patros-ki

**Comment by griseau** [comment]
Thanks for pointing out ! Thread concerning this question : https://github.com/confluentinc/kafka-images/issues/128
