### ISSUE TITLE
which image version for the Log4j Vulnerability in confluent platform  

### ISSUE THREAD

**Issue by bjlvfei** [confluentinc/cp-helm-charts#576]
Hi Team,

Did someone know below images for Log4j Vulnerability(Log4j v2.17) on confluent platform? I'm not found the log4j jar inside the images. 

image: 
confluentinc/cp-zookeeper: 6.0.1 
confluentinc/cp-enterprise-kafka: 6.0.1
confluentinc/cp-schema-registry: 6. 0.1 
confluentinc/cp-kafka-rest: 6.0.1
confluentinc/cp-kafka-connect: 6.0.1
confluentinc/cp-ksqldb-server: 6.0.1 

Thanks In Advance!

Levi

**Comment by bjlvfei** [comment]
I have found this jar relate to log4j inside  cp-kafka-connect: 6.0.1

cd /usr/share/java/kafka

-rw-r--r-- 1 root root    12211 Nov 20  2020 slf4j-log4j12-1.7.30.jar
-rw-r--r-- 1 root root    41472 Nov 20  2020 slf4j-api-1.7.30.jar
-rw-r--r-- 1 root root   491849 Nov 20  2020 confluent-log4j-1.2.17-cp2.jar

**Comment by andrewegel** [comment]
Please see https://support.confluent.io/hc/en-us/articles/4412615410580-December-2021-Log4j-Vulnerabilities-Advisory

**Comment by bjlvfei** [comment]
Hi @andrewegel 

It's very helpful. Thanks!
